template_path: bridgeworker.yaml
stack_name: bridgeworker-prod
parameters:
  AwsDefaultVpcId: vpc-0dc0283c11575e03b
  AwsSnsNotificationEndpoint: bridge+prod_ops_notif@avegenhealth.com
  BackfillBucket: org-gvbridge-backfill-prod
  BridgeEnv: prod
  BridgeUser: heroku
  BridgeWorkerEmail: bridge@avegenhealth.com   # same as BootstrapAdminEmail — Bridge shares one account
  BridgeWorkerStudy: api
  BridgeWorkerPassword: !ssm /bridgeworker-prod/BridgeWorkerPassword
  EC2InstanceType: t3a.medium
  Env: production
  NewRelicAppName: bridgeserver-key
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  RawHealthDataBucket: org-gvbridge-rawhealthdata-prod
  BridgeServer: https://bridge.grip-research.org
  S3NotificationSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/233151233756/Bridge-UploadComplete-Notification-prod
  SynapseAccessToken:  !ssm /bridgeworker-prod/SynapseAccessToken
  SynapseEndpoint: https://repo-prod.prod.sagebase.org/
  SynapsePrincipalId: '3591871'
  SynapseUser: bridge-exporter-prod-avegen
  UploadBucket: org-gvbridge-upload-prod
  UploadCertBucket: org-gvbridge-upload-cms-cert-prod
  UploadPrivateKeyBucket: org-gvbridge-upload-cms-priv-prod
  UserDataBucket: org-gvbridge-userdata-prod
  ParticipantRosterBucket: org-gvbridge-participantroster-prod
  WorkerSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/233151233756/Bridge-WorkerPlatform-Request-prod
