template_path: addf-export.yaml
stack_name: bridgeworker-addf-export-uat
parameters:
  BridgeEnv: uat
  OpsNotificationEndpoint: bridge+uat_ops_notif@avegenhealth.com
  VisibilityTimeout: '300'
  MaxReceiveCount: '5'
