template_path: bridgeworker.yaml
stack_name: bridgeworker-uat
parameters:
  AwsDefaultVpcId: vpc-06153fdc5047df63c
  AwsSnsNotificationEndpoint: akash.shinde@avegenhealth.com
  BackfillBucket: org-gvbridge-backfill-devstaging
  BridgeEnv: uat
  BridgeUser: heroku
  BridgeWorkerEmail: akash.shinde@avegenhealth.com
  BridgeWorkerStudy: api
  BridgeWorkerPassword: !ssm /bridgeworker-uat/BridgeWorkerPassword
  EC2InstanceType: t3a.medium
  Env: staging
  NewRelicAppName: bridgeworker-uat
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  RawHealthDataBucket: org-gvbridge-rawhealthdata-devstaging
  BridgeServer: https://bridge-uat.grip-research.org
  S3NotificationSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/433864969993/Bridge-UploadComplete-Notification-staging
  SynapseAccessToken:  !ssm /bridgeworker-uat/SynapseAccessToken
  SynapseEndpoint: https://repo-prod.prod.sagebase.org/
  SynapsePrincipalId: '3573485'
  SynapseUser: bridge-exporter-uat
  UploadBucket: org-gvbridge-upload-devstaging
  UploadCertBucket: org-gvbridge-upload-cms-cert-devstaging
  UploadPrivateKeyBucket: org-gvbridge-upload-cms-priv-devstaging
  UserDataBucket: org-gvbridge-userdata-devstaging
  ParticipantRosterBucket: org-gvbridge-participantroster-devstaging
  WorkerSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/433864969993/Bridge-WorkerPlatform-Request-staging
